# Build SEIMS on macOS using AppleClang

name: Build on macOS using AppleClang

on:
    push:
        paths-ignore:
            - 'data'
            - 'doc'
            - 'gui'
            - 'knowledge'
    pull_request:
        paths-ignore:
          - 'data'
          - 'doc'
          - 'gui'
          - 'knowledge'
    workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - name: Setup xcode
      uses: maxim-lobanov/setup-xcode@v1

    # - name: Check mongod
    #   run: |
    #     which mongod
    #     cat /usr/local/etc/mongod.conf
    # - name: Start mongod manually
    #   run: mongod --config /usr/local/etc/mongod.conf --fork

    - name: Install mongo-c-driver
      run: brew install mongo-c-driver

    - name: Install GDAL
      run: brew list gdal &>/dev/null || brew install gdal

    - name: Install MPI
      run: brew list openmpi &>/dev/null || brew install openmpi

    - name: Checkout SEIMS
      uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build SEIMS
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -- -j 4

    # - name: Test
    #   working-directory: ${{github.workspace}}/build
    #   run: ctest -C ${{env.BUILD_TYPE}} --rerun-failed --output-on-failure
